apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lnn7A1W6PAQ77fe3OyfbA+DnMXwLJN/4NMGrIdpXxEm5a5L4,iv:dsWLKNagBmVglNVi4mAwncFROfITqkmuaTIW3z4kY68=,tag:8F+YHVFLV1he/6jPRrnLjw==,type:str]
    credentials.json: ENC[AES256_GCM,data:Q2tTA3lMMatnVX2yruanhnjM9K11eEg0yWaq32FAXhh+uE5uU0c9R89boC0lTWPt35vhwYHI1BYRgCbiBIWgkiwKYpPsjt0BayBEbgvH30WNS3nyQZgQ2ZH4a/5vG8oPTCHqKEyV+TT6NqX0QAOKslPnyf2oIvT0jMgO5RgxX/wJbhoXLMlPrFdXQ6fsQHLT/BndJRO1/b9KNqyJBplvNqrJ6bJ4Ob9LYTFnORpjdg==,iv:Jkfw4G31voog06Va+6OIOVCNdKP3EqUxpJcJikF9/BU=,tag:3qDhj1K4Gh0zHl48y2zZKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUM2xrblJmZlgwT3FtUDlX
            UmlsQit6Qm9NUXhYdnRhQ25RUzBmWUVWQkhVClNBd3lrZnI4RDY2S1J1N3NuSHhI
            bTNDc1AyeHQrdElZOTVsNGkyeUtSMUEKLS0tIGRpVFRKYjg4TDRsOVlndUhVczZR
            TkFERzBvbmhnU25tMjJOWmxYWmZ0Y1kKkZBU6AOiFtBjw6NdcXen1BEF7wDzXtQB
            fyTfqxBkDCk3czN2i9DD9fcQRzje5ClDC51vt19ETTEsIWoicnikRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:25:03Z"
    mac: ENC[AES256_GCM,data:ezUGsTF0IQf+NXnIYe1enC0S/GFv+Ucd5xf1r7lVz/j1ZHwyBKM9Yi5STLecxEwNMHFeFJoa2qPJVjh+YEF7V7bgAXuO1a3Q2o9OUYVGJ389bYj5t3ZCabtvHDVpcMQ1lnpi47YSdDlsnZJXMCjDCUyooHWvKof+Atku+KhMD90=,iv:bTAhZZ+AjVQ+gsAXynY6cYyxRcMuU400DSritqXiS7g=,tag:41PyvqYpXmmNcauwHuCcYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
