apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:s8k/b6tntIQzyg4aDlnZYW/6Jn5d7WkM7yyJrIHK44Mb5+JW,iv:DadmpKPmPXPUpqasWKvfBhWXisBrQSfm7KTaKpa/R1c=,tag:UG0gxNxyzHxn9CnU0Hz9WQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:fKG1Li58McEhN/vOnNLl9U4LdHzTllF4O7zt9RruGZ6vsoh+TPZ3CGmI7rivTAEHPJBOxtDW5F+amFK2fa2NnEkv4xgBSRgsuTFBaPbwkWU4ihuqrrtRxjcqu8Ns+k/eOneFUDmQKAyWNOcdm8ieODy+0Xq/YPxkqpf+ZprSeGq+23W6wz2z+7gOpsCV3W07V0JTO3f5HqKvRQ2ciN1lk7rIudE7ij5ERY3JIyIVBQ==,iv:Is5c1LQ0/H+EbbVA7e7TlMYFbvpqMAUFoLl8Spmq6hI=,tag:84nnyC9A3t3wL0OjFaiG1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORnlqdVZMUCtWVFFWRzdJ
            WTBPemIwODZIdDRVSjFIU2lGY1ExcEJ4RndJCmY1VXJZZW93eS9CNHh2Qlk3a0RJ
            cjM1Y3JqQVNMVWlRbXNpVlR5QmRrSU0KLS0tIFRwZWlOdDFPL21CTmM2YmJwZm5V
            d1MvcjVwUTJ4RWxTSUg1SkR5R3ZIMWcKTV/ul5V8vQGxZBMwOl0cUfxpRHkZZAUS
            iOaJ0ktc6LOQfIzj2Om8YVIVsQxAsAFnqCVyp8Ij0IwUw3ofmwhQtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T00:10:52Z"
    mac: ENC[AES256_GCM,data:fijsMV8wmxgRtdM2FARyfLzpuzFFpM48GYBGoxHAw28FVqiVxr53fbDgNffkwlYC4qKZMmLqHEtcspnHVKTsaFPqpr/1B0lNCgSpI452iZbkbaEb187vliwti7GaLZAPIxZaPEXo6jNx1PBE9708PUvmnVOFNDNVSwX229nk5/g=,iv:WCjkvMucLKY2kjeP70qKZEx6vQsZIFUfLBn4NH7Cnvw=,tag:WMdh6OCma/Rslsaq718Xdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
