apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:q51DAGXhZmeudWL7AgdS/KEy/Z7tnXPAfbbXTFI579+7Q1Xt,iv:sJxC5mnekPpOlDIiXsadaNouPZClMK0qoCaBmo4g0Y8=,tag:4R+wCq8QoocSQcLPOQEYJA==,type:str]
    credentials.json: ENC[AES256_GCM,data:W5UKqpbcLoAHy2aP8rRrTjOdDTG40mBPoP/nwYlqJoVv+VKiESpf9YH8Cm47PBSF93E/29048e9MCuuY7HoVCKUkpbrBTzcHslwGtlBMcU1EeMEsrZqyKwyOgWiMa7gbkAtgVD/bujpQG2UtA9kF7WEy822Qzs4JhxGWuY9OXJY6YTYwY0WJpRVMYVmAgnBWA7uAlxJ6qYhadE6S0QZlgopQ+HIiwOfSG8cx2ByaUQ==,iv:VpAoMGTT0acyV82rX7gHeYfkd6Ev+o9OzYAlm+YJV4w=,tag:MCnxsvz+6XnIoOCDQv7fvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VDJiSC9OSC9XY2prZUpr
            WWFwbUEybVNleG5LaEgwaUh1dTNIbjByZTNRCmlGeHd3TVJOellaL0ZRb3lZaTFD
            MWN2VktNOERWZHFzTkNRL0dkZDJZY0EKLS0tIHlJWDByUnFFVWUrcm1qbWpRTkJG
            cEhYeHJCVkkvZFZWTFFJK3NaUnRCZmMK0Vl4M/q2DuSSnf+1P3c8QvV1Rzwaf5vE
            FtXIeQy1WQiUOPMRblLONpmC3v2KIXMyCnYBsmIYTVoUNGQTMgF5vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:30:31Z"
    mac: ENC[AES256_GCM,data:dGiak68y53x5rxm2UcLu7tNK+fK5b4ch5SXU0HTyNuosdNT+4eiGajJiXRMjwsqOJQFMEEl0oQKLKm/7aNA8NexMx8QqxERYuTrdlfn1cHnjgDEM46hXZySxFAKV0cBa22GB17Qf/j9uWlZhJtmusp84wvEZs+q/aswquImIjWE=,iv:9PNW6QPsGnBn6zvLDbVzhSv+2NaEP/g8sEBSngGmKGU=,tag:0IJB+UTPvTK+az72u5tEMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
