apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qhXYWLUJh8xiKGWyuq0MlcQqsA7Y1i4oyLjAOA9pZWxMKf20,iv:ZVwo/UKE/qD8aTV0gB3e3c1UhZ4ednZ1LZAmtnqKlt8=,tag:kCdt0fkar+gSoxns9zbs+A==,type:str]
    credentials.json: ENC[AES256_GCM,data:PJCV410TtX81X4kKd9qEbygX7NWt+ju8tSOD2pefwrR58WOmaIR9R6ALt+ifIJzAJdgR45bPv6sj5MzPU2aeaZXWLBNMx0uBpH2O2uiTWu1nPCBTDo9F5+fa3cN9H4LisA88KpTuSpBANf5HJFNGnb5PVWAMc4ILZUGK8911NvmbY1o+E1KM9nBdNFA8ocj8BH88cVrwtCd85RRsH57vwmC4QUS5rAtt7nqFS0i+sg==,iv:7ibkKeeBiqB1zKeFZNuAJlKZqaXoLPSwaB2VsIjed9U=,tag:4ogyoqCSVOc05QU+MTemJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSmVyR3FhYVBnWXBveHFx
            b1dRRGo4YVB4WWt4ck52V2dWSk10TlFnUlNBCndIUWxKdkhsZnptcnRsby9JWmpW
            NXlLWE9QZ1pQT28xYzA1V2FObnNxYlUKLS0tIDNGZkUrcnRFc3JrbzVva0pwekNl
            clpZU3B3c3ZXNjlwZERRWXdpd2VjSjgKYg/J91UQHOCnWnYW3/9tVocQfCHQmxdF
            FY8UFQWy8D9NzZ7miwhtgSxjapSxkzPOFQ+jtoMjmp3LISVmj6Qnzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:37:26Z"
    mac: ENC[AES256_GCM,data:WHLYNKusaBdLbb6lbzDhoheJHanSgLgAnAguk+TOp+z8CPIXjyj3ZbFaZN8tOLT3nSTgtbQ/ZKOdKddK/Nn5TGz38u72m4Qyh1PI/1fpw8pWFzoXhcTqZAmAc/7RsamEuBLDpVZnuoICZ23e0hv2NbzyLQPmJNbFMSG+zeTpCQo=,iv:3gwgPTX+SRSvpqGiGp8Fq8wexEXlcMvTvPtB7XEM6b0=,tag:eR2KWKCU9+6Y8i0uwh7DPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
