apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Pm89VO/Br54cDh4i1XfYC8w/m1DX0mTDEnSVMcxiJksXZOer,iv:JWotnVSHevMHBycOVErXJaJ//D7+3IR5cOZbNMnxoIE=,tag:QKc/THJuZ4/SRmRY1qzRTQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:LztbYx86TRJHYMhgszQxnSSbqpf/b95QbD0ewo4BCIiGNThzvJ4gj3sfOL0oTU5x2hT/SsHop+2xlStQiyhR/hBPcYy7+wYBN+tJzWIAhXJZlyT89ECF1ESxd0OzX8svPdVbd3DS0JG2jqafC/07VHojgbDAeREmLJ5d/R7plR28z/hqDe01/wVT6v44IHmmUNDFOVW338KYepskl1bAqxoTyrjBLzqCbOPiJKZDyA==,iv:kuZ4Y8QKBdkdbceNPum5z3KfffZVEo0spXsxDSbWTFU=,tag:PahpQmuVOk7/hlrnmab73Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSFhoZmZXQ015anlGdXNo
            Zk0yc01wSFllMU9DZXUvbXB2MU9DY1Qya1hFCktRanpRU0gwWTduYTl0K1EvcUk4
            YXcyODJ2L082SFJ3a1c5V01JYUdaYjAKLS0tIHpHRmlac0lzOHN1b2xoOUdOSVhB
            MzJjSDZLMzNwVEJlSEp6QXFTMGIxRjAKAb4aYeJdOj1VgXBylQQikR2tqTVvSEE5
            ZJMXVWZEIXM5rh0W6n4rnSzKSHnxn76zcs7CYF/SdCiEXr/Xr1ZJyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T22:20:31Z"
    mac: ENC[AES256_GCM,data:U14gWPFAs0XzC9onZvVJsp8AV9h4stXXsxMw7RYJQoP+JzIsXDnF+R8ZyBNTt0HJec5QqG0FU2VSRdRerBPh3RXkOGx9hrvTC1r8VIwUssxp5klqsh1stUz5smtVenLpPJAiKtdSOcmMOu+rWcUu48X/yLpPqOmHdEki1w1eKQU=,iv:z7LLk9L0jKKpZaoxbVqcJ+3m4xDxupBGj5p/vySoVTw=,tag:lZ1MJK5M2ceYWBFHagGI8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
