apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0u2jBQgvYSYxjRRb4RuquTHyflMP7olcp5jqH938lTfdrvG6thOkbQ==,iv:tlgElCvTy/gvbitr0ErwFoY6QER/SBecFd17InwPYEs=,tag:v1mkmGOUtiFCyeLsUe2ymA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVB1dXpoUDdCSW1sQlJI
            eGtSdlpJU010N1RvdHI4VDdKK1haRnVJdVNNCnpSRTlWUHVTU0Uwb24vbVNNUkdP
            cHlIRGtWT3l3bXhrb01aREJsMFdLVjAKLS0tIGtOSTF5TzdoNzRQRCtxMGVmVWtS
            TEtwMjBxV0FKVEhrbDZKZGNUdlNkSDQKUT8ovWu3YLTL1POdeW0RlO0HcQYc0rhJ
            RaEZPPxC8jksJZNFa14+OHjkYf6Q3BmI1kTleilqkXBDCxqGE4SEiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T01:07:49Z"
    mac: ENC[AES256_GCM,data:WTVu6O9yptYjf8pAk0V4Po3XVja8swatDAiu3JfjVcbOhxHVrpYTGpT45xA1PZUfv88CrCzBjt6mWLnyEiN8ZFrR6XgJ59hVx/Hjt3GEEnYS7cQX9RY+FZQhEbmhLLIx/xc/O9btIs39A7sdV9bsx4G2Bsmrl5nyOhXs/UC+vUo=,iv:8DrK/+Tn4fize9m3pcN7A85Na+sGpJsFoDTzRku53Ns=,tag:nhxVMR4y0wSfEq31bpTdog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
