apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wpUI+Zvg8ozxBZI9q+Qm34UhjH3aN8C1BEazJugnhwhgJ5DoU49EGw==,iv:hEovE6r3hO4+5k4rgUNnBD64RznpZXLgA8BV10U8Xmg=,tag:79JBjC+WR+TPl8z6q1c7Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRWl5SXR5Si9aMWRMd01M
            dzJrTG4xeWJUT2ZrNGI5dmFra2RreXJ3NEd3Ck5ja2FHNTlSUjBpUWJIUXgvazVN
            R2VzQXFZVHRGRU5sZmNKMzJQcXEzMFkKLS0tIHlCa1VaUlZpM3JEaEtBa0U1Rk1v
            RlBnREk3VjYxcDBLcC8yTnNkTWJ6L1EK0LWQT1So+6HWKmXdQ6dcbXTiN0Gws5Y1
            ZdmZOqmax0byjWVQo9fPC5KFVMStHodhpmR5WPigfRNA6TGcGoTA9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T21:50:08Z"
    mac: ENC[AES256_GCM,data:V8p373bHrDV0dqDYqY0Mw1HvRNBNbnOqFaweTK2L4A29PeQuueD6cEpbrcNkW2aKYdzt3Zvr7oulefBkdhufjOkGcDWuIA8I/M/811JP89xdIXFSYqhEJ5os79o+de6A5bM6SdPyh2SUEeyYaihwOqg7UQfVMiVnKK8Mb/T1pvQ=,iv:YI9KRpdjgREBRA7KV8JdLhq04vuGjnCohCrifoaL5qo=,tag:4DQIw7f8yjQH4Un5T2M0Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
