apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:idOMniODX+gi8M4a5sxnGERuVgXc26QkplP7YfgkM7wmN6aY8Gu0PA==,iv:49PNAORQR69jDBuFg49faj1ShDB3TT88AuQJc/Hly9s=,tag:adaakhF5uK+cYEhqFAoxlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN2pSeVM1M1kzMEl4bVRt
            S29RemFCVktMcHprRjY1cGw2OG9leUU5WEM0Ck4zMGdzQ1VzellWRmhOQ3NBcGRI
            aGRWOWdwb0RzVm9FZzQ3N3BOWE1laFkKLS0tIDJvSjlUYmFnbElMWnBxRXhkRUhP
            RmJyUVRPNVBweVZOTk4xOTQwSWdUSkEKUFI6YNtvvONfsN79lJWEEJ32Q/58OVRy
            p8garoXsULMC/PUrYOpLOUa4C7wNuYQYffF4Gexj8unH+EJjEbWWJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T19:39:43Z"
    mac: ENC[AES256_GCM,data:py7/sKUGWBxpiFRBcfyc/5/AAyeIp8BuIOOKAvwhl+U4yWNWHju39SRVGRBYRBIBT+xovvMfV24I67odDk3ZyQdK6WcikXgdmJMdLTrnEmp5v4eQ7d7ByfzCZLcNBS2KcW2V9GTsJqAnb1JajKjwLmNRH1/niUQ8uyNetpuI6wc=,iv:i41SbiG1ByVZ0ZVgAmA5d7zdAMkO2EqIMIYs28qgOGg=,tag:es47O5d3hXehml60qEbnYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
