apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jIpM6j/T3VIk80eTL9CdqKUSq15/Y6hh5FjC6bha4Smu78j+YpWEmw==,iv:evcdkSu0iERPNi6TUok3wedLsnqueMe+fG7Ov1k/PIA=,tag:a9Asr5pdP5i3DW/936hrxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaE5wVmgyVEcyL3ZYQnFR
            clZiUmJZNWVzOVM3em4zQmpCTloxU3V0R2dVCkY3dlBSTWJZNDVyMTZaN2dyYTJu
            OUEvR3FjL0hCRmFueE5vOTN2K09ZbjAKLS0tIDZ1T295RXVsZ3VvdHJ0QlpIRWRP
            MVFXT0JFR2RnVHFnbkQ1YWVnVmdvZEEKM1kyTv8Pleu325E7SYdP6IX9wULpdQes
            sAJVcz9++n7VIVHN7KX2AHWJaIuBzjUK5gUcvTeMkEG1mjsL4cgyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:k5d4tLDFfuwIsnKsfKIa9f5wJi3gPAQP8hsN+QRcTx1B0YQ9rEdkF7EUldDQHIBJuTZirhJycurXHipHAjmm6AHXZ0D+MvqaKVOxG29m0zgPytapTjOs4FAy7es4IEWgnNkGlQzrKMJiwkTKQ3Vm5fJVR6lz86KViGKLzrw6/Fk=,iv:7LPkVF2LH3oSMIIjl1QFWH8MDqaFR3SpatGD3i/J00w=,tag:SWJL5cQxDG0hViH3ixyQSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
