apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:HZiOa5cFweEMonhyplHKAM/rsn9FRLoQ+zG2N58YAKgvUfd4nWqWfQ==,iv:pkGl9URVOQNYMK6T1YQQEhW8IVE80OF82By4UtNkijY=,tag:NLP4fhw82KnjegudtA1vdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMHhLSEpNZTZBS2VXWk1Q
            ellXOU5yelJHZXUzaHljTWlxbHZWRG5UQVdZCkRXODVYeXhrbVRPSVhQWndmcmJU
            NkRVLytRd2lGYmxpTllYSFRHK1M1ejQKLS0tIGFRNzRFTG1rOWkrdHJETzFmWmhq
            YlBUMjYxWjA0V1RDUFd2aVRaY1l2TjgKO88LWVBJ77yNmbe1F2fwKTEt3werjA3M
            5Qctbwg8gt2BUgr1nybyYLLKJgnBUkPiWhqIn1Al/LIAet5AAnFNqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T20:15:58Z"
    mac: ENC[AES256_GCM,data:1neeG67wJCtn8rQ5qdf4YjGC2sdjxmr3+tsnhQViRJ2yo8hp9HNQBzNd1Hx6VRjqBkHzTNVdZU9z3So4p4pmvtsF9HbxfGtZABAExh1m4WlhY3TrGIOzwpC4V5xbQDvQPG8vnafMqUANvos30wlPEQPBMIwWuRtL7QbK18NuhgQ=,iv:ou4z0fDPAC2SHhETRRzzRlsF13NgRwnYPc4IZkYpmZo=,tag:SttV6qVcTSSSEJmWO0ib7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
