apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VQ3SwYg4sp6xN5uWADFDhSGUuAx+uPGJCTgb3XBIUvdTTVdWSugm8A==,iv:bwUuoZkw4KR/cV/3QLWUBXGD5BEL+l8M+Ger+dDq3eY=,tag:ts9Jr26gIadUpDai81mfzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1azVnV0NoSWp3cHVjRkVj
            YTlyT25hTEVpWWIyejRyQ3V0M1liWEpRWmlRCkJZa2FZb1RvVC9CNmN1blVtZ2lX
            a0Fwb1JTcU9hL0tvNGZPbHlZN2RWSlEKLS0tIGpwazQwKzN3dXVhV003MGp4dnZV
            RUd1bGJFVkpUeW9TcVdPR3kreWxwNDgK6frHaahc885hpl/Ky6zJFAcdqGyobo08
            hzO5ee1ix8JpLwEZYFxhxosUTk/U9PLZo31sfBoIcYNg2W42ayfDRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T05:45:58Z"
    mac: ENC[AES256_GCM,data:OwROdUvo+Yje2yKUbib0LmahrH6XMlkhrCSg5wzCm/HlutOCD1CC0f+n3o7b2QyZ4CqYm97LkJz69QN6HOxQ/0vtCy5XqpwlMDDVWPpXW8qVqAQ3ZbV9jy+f8ns2QjlAIXHODFZYCZVzBL8EghkaNFOAWFN+BrRMQY4tg3p/tUQ=,iv:+JSqD1tgtX23aKXrCMccw9i4MlI+NQkWrkwHXdZl3lg=,tag:YyuoJrBhNCSUDztd1hvxBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
