apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5HLV6T/2bjFZneFHHMj0p8D2sS2QB5chxY+bNb/S5aKticCSL36lvA==,iv:d/TS1NVVDlqJPwfasBu8SZqKl7jebJLk1SgKspOIohg=,tag:f/5Nswti+siEa0VQLTiCxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4djlEQTZkRW1tMDNrU1l5
            MnBWSGNienhseGdybWppdlFhekhQNVdyK25NCmphRERnZTM5MlhqZWRFZllIUkh6
            d0VsUThBcmtvZVhnUjNzRTVPampxbzQKLS0tIHJqM204YWo3d29jZm5VRFNyZU1t
            MktVVzlqbU1UZm5kVnZpazFmeFJhT2MKCpUFuxFCytvCkVcdx09PFihu3uMVzQUa
            PtS27uqB4BbW87Kc7SfZUtorekobmn0YM7V+3gSEWoyCyqTUKlXbLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T20:16:24Z"
    mac: ENC[AES256_GCM,data:E+9tTAzfx0JJAekwM3mkOggqM8rMggMdLsbh8J5I1qbZVt4+A64ENilJU9QFEqrRpYq/SYuW/Bu2AmXUPXGSQf2Dqn2SthY7Yr+sJ1YI7frX3MPWz2TPdKfWv3p1vPnc5DXPTUIsND7SqaDq38luCR0422NjrrIaITwOru6nBys=,iv:lEP4NYRABQJMFoqvl7N4yL/oZpgAgiSLUezx7YqUnIk=,tag:IEW+bpqRjNr/sh2ArJ0aWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
