apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rX4s5fq6LGokHoIjTsQyyL5EwCIAs0vuc4sVeBs9frqK2WUmiltKNg==,iv:1sUJ+KynUXIpmUFv6xWO3uhpzfJEhKVU/AtUvjtoFDs=,tag:2QKcUHduIQ4qiEmGnqeY5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZE0wYlIwbW9lVFo5V21M
            cTNpR04yNnQ1dS9qN2d4aUZaR01sTnpzZVVZCjM3VEJ3TTJHbVV1UldTell2dGlO
            czJ2N0tKMzJhM3phcFRlbzhWYjJMRlEKLS0tIElVU1JqTThKRjE4d2gyRnI4Nmlj
            LzRQYVIxWTRidjVITU9aU2FKc09wRUEKQMjuiwlP+bsTuDeuXES9LZ6GQIPUMCuQ
            akOJoouiT6dD9WK8B3BGh7ljTxZoEKmMVodIqG5wapMgJRD7zPgcuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:45:19Z"
    mac: ENC[AES256_GCM,data:XWD4Cl2o2w++ZvrvTIAZ5KBbLMRxPaJU2Vn1DapQw7bBnlnF1/MwMVNIw1TssQc2+m1PGD9Gq/KE5JX3Gx46NRpmtnd//NU+ZH2IIXMGg3ckdVumSBmvLRuhsnWXyfloBILIJma4xtkRAxBq5WKvEnbVRB3IWG6d1xUdBvtLlig=,iv:Iode5G6W+ZjO7ybAffb8iGYUwTfy3FxcS9BxB09tHhY=,tag:bNbD4lGOXBUqG4z6fY1tmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
