apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:83yYTJrU2a6oLBXWEw==,iv:ao1wtxqcct0OzhyiQCq3oTyH+VoLVsPhGRDAURtUeBE=,tag:prDPVF4EMU2Vvp4/SGZ09A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:lrZqsELxuV5ZznvoDk+SR+ONiuQr2IGovDmWaRsT6rXj,iv:N7CEDnkTHPRPXibGD7MRd4Py0XJ8YWg7UvCLIp9k9zM=,tag:2qdawGoWU1/b1WBPlBviXA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0jbmL3H8WUiAfgBPLnBNC0lcVqxIaWp6eT3Mn0/wNUbWMDgX,iv:a71CVRix/sOKjslZFHEFcN94UQ74cwA1a3XYPpniKPs=,tag:Fxe8xJttENUOoKcAa6lamA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhR01tTnZyTUNoSlZldmly
            QzhvdWJQMzRCMFlYeitHNXhLejhreDFRanhFCkQ4UlgvalpyZEFlK3BCVHcvSG5R
            NTZRQzZOTDZLSVRLWTNpNHhhdTYzZG8KLS0tIE5YZzJSMWI5aWNLN2FjM2xFTEpv
            Smg4bFhZbmNmRFlYaVNiZ3NNZDN3eVEKyttcv3mkMC3Jx/B0f93I0Ql/fB6mMFlf
            R8wmeZx4PIBNcTt9GrmYXcQxGEzO+Ew2/aftNopFOgZS3TUVItz+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T19:08:34Z"
    mac: ENC[AES256_GCM,data:38DRr1ZSYUSrl9XqHZsBsz2CNtVlGotoDISa1mopvm4PThHntSMAMq7ernOmZud9S0JTOzKsQLjf/JZ5gfhQNoTCeRBi+k5OmMlIwzcB9XMmAcZcQaGW98WlpjG/ckuB7Dhc00R90lc03KH4U0CSieyusBlFrBlr39D2h12bbw4=,iv:k98mcuQTZE4U3h0tga+MC3BmAnSMBw3sqE5ImKtw5G0=,tag:7q2O4RvOLHoLJ9Z8HwvY/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
