apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1yw3/UwDfdqLHT+uTw==,iv:LEPX055CWdwzUHJOtlIRkY9ur8g5hZ7n2ALq2h04iY8=,tag:lvZCXpDyUS4CEvxKeNUwGg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YaKDeaHL2RugCw8dZfJV9h8FA1PTROfqjOzMrHCCRjPT,iv:T00racXdp6kO3qln9qpzM+l2Mnj7dIQH/076OF8Utxs=,tag:5z15i6okW9iJ36vBwv8X3A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wRiSRrL50prsIHKA0lK4cQUNFkA4E2fxzeWzVgyl6rTtRh0u,iv:Z0Az9ozMc4Ee48vfJkIWN/+LzRDpWZnaccstKQScAYc=,tag:wl8OqjvScBEgLDw4IKu5iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML0lVdFdsQlBMQ0tzR2hO
            SXhSM0lSRDVRamY5cG95R1dPYzcxOXk0Rm5jCkRLamk5clNXeWxoUTdkTVk3NkZz
            NHU2U214aUU5TTZYKzk3MHhMWUs1Z1UKLS0tIEpycW0yRUJhOUIzaHFiQldray9M
            M3lsWlZ6UkF1M0RNWkJuSjdXSHJ6Q2cKWzrOseF4UwqdKwSDrOc5iteghJlPc+fn
            +A1QSWEaKYg3fgXgp83m1uGk0PS2BuZsbxxwhXPUCAaj58CvRDJNPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T03:28:14Z"
    mac: ENC[AES256_GCM,data:d1g5zlLB1Whu3GelF+BqzIoEBcUhuDbGXQjwAhqSKxT8B7AJUU9NWdyEYa6mGHJwoVAk0cJmyYdK/1aMeGaj5Sa30iZdfIfLtbYRK5W39zJ4NtzpJM6zpZk1zm+LSoCn0ZjeeZB1IlvgbN0CEss4nc3VAMFYoqpxZNCGbC9mtiY=,iv:n08rq1L1Na3+pcbgAkuJl+V0Tv4so+k3a7aUB2l5hS4=,tag:3L/hymYe0UGG568YTtkKJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
