apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ReG1cCIBaYHfsNZIMw==,iv:x/69m8GJWQwdQr5TncNEwb9dFYqBKMHh/k/UxD+MlP8=,tag:YRHlI9XM5jCe1ab4kq1jHQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FCZO0x4pQxFpmaHa1Y4eKP24l9YnkMuY1DLPgiPWuuA3,iv:HFSeUeai2wsTgLvH23Xk6WtOXEEctc+e7Zc3SWRvLS4=,tag:RPWN+2X4jx9J4Vfhf6nICw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gRhtUC7JhcXUMWyJQkeiPnWCbRpQ6VYkgN5dN8JeNi5ZUjDx,iv:ce5r2txCQAqU0h5KYl9YEM6diGtwug8QZgGvCRwrX8s=,tag:iHhvVxb2p/qDbNgYFMfA9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaTdCZDBOTFVpbE85b2RR
            NWxhVGlZTjV0Y0kxeDRCd1VCcXg0WXR1WVE4CnQ4VGxMRE8wNWNYMXBySWErM0M0
            MnV4Qi9NbDZCQ1V6VFVPNVQ3ZzBTQzQKLS0tIDVlYTRrTmgxanF1am5MeFIwcVEy
            Q1Rxbi9zTnZHY0ZJMWcyU3FpTXo1VlUKZ3VHXFclk4tEEgMyx4Zo4h53tJNzK3+u
            AT3P8NqBab/c/SDHMkcBnUjLgvB6kU7KyUOCyOX4H0hP3ElmPeylsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:45Arc6ADOcHM+0/JHus+Ne+zSyncHDUcQUXKQd7i9Td06N2ZOqohtn/E5SJMakzOi45283jLrXoRLRi+CnQGm5sl2SjFcrlMByjBAdYO2eCALwjmJClml/8RRTGpgjPOxWMa2kGeNu8m/y2ofifwEB6ViJ6CBRO34TerAF9Kx2U=,iv:ePHm+FPK/I+8huQpZzL4tPgZ/Oa/X07AOSwxYYQ0Bak=,tag:YxpX9oBTRf0SltBohV/GdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
