apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3/HQdUGPZzYkcZsLbg==,iv:sQtkDXyrWA4UIiVMqOxTy/nFW60jYT++KJgupkKLHks=,tag:PwwiN7V9ZjvoPsUYtzuo4g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+B4GzSPvUXDwsgIq3BHZ7i1mTxEcZu9xpuDIgatZQHLl,iv:+v3pYf0zDeukEP19eq4B8nZ03Pgoxdg2LhpwKYE/quM=,tag:MAIiewrxRRpAuIZojDXBKA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VKI+oDm684ZqC9H5suVBbUNtRMokn/yVCttIzzPCM5KHzT3c,iv:FZuuUfu/wvgI3HY7IVqn6n82jiievsPV3Jdl2ixyLfU=,tag:6QwQqvhDmgZT9JBpA5+1Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1Uza1VNVGp6K2F0YzJ5
            YlVuc1VSeDZ1aDNEdWQySUE4cFBaa05Ma25zCjdLOVhCY0F1QzNHU3RodUNmWVIr
            NXZONUxMVDVGUXBPa3RRZFBlMEhlTHcKLS0tIEpOK1lIRmNmc0REUDVDRFVvM096
            VmNUVFdMRm5NZmpCbUlIN3NoSUx3ejQKaAw7B9S0xSweGNgi+RtIdwu77vjdY+Rs
            pNqTwfmdASC4mDVkpYIQFue30rrEillqtYyO7oZtqxA8y9plilTNaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T04:25:50Z"
    mac: ENC[AES256_GCM,data:azvtXCseeShxOHx5MfWbIiACtAOtMqBQwQ9QCCfOaIhPC8IAXTh2c4zaxc26wPZag4oMVtjQqrDH+SfM1T4MrU/+JVr/M81V/3MOJiG4cl5DO8uQRhy1cL7Q6lxLpG0B8nLGzura5jMUfjJYiYBoZlwXTgUM1e3fyqTegJoeO2k=,iv:ODnaZL9yW2af2dVLtvrm02ZHmrblDdxs0D5eaI7uOyQ=,tag:RIwPguWB56mNOfiOS315zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
