apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bnV6F+Zrj86HJP7iTQ==,iv:hawslNPwGKWHMVrCab8tWN9Go0eN6mJ1ETwrpoDedTQ=,tag:D1+EHEySYsERJ8wTxcKQdw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YcETExvxgmQfTx4A8qEoc+MTEs/NvQAfbiXL05h9oDtg,iv:P49P14JRTKzG7e0y+7kMiPVsnDKIkD5iVVdBLO+HUnA=,tag:GKFwrSjGfVRaiFDaM2xLRQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:u+JKcgBaenyI8Dk6x7cfzvZvxwNDuKdqzCNRAKa0DZOTi7dI,iv:P/+K+kzjGGfD3agPpS0fwLymF3r3fdRHtzfdCOwGrtI=,tag:9JU8yr6+LUN0FdXLeJ2vEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WU9tNGc4MStyZ0hGVVU4
            OGc2MHpzUVlnS09DRnJlSlduUjI0UjlpaHdFCitDcGZjNnhGRFg3NUNzK0NjOVdi
            enMraUJQcm9NQ0M0STNpOWZ3T2JQM2cKLS0tIE9Xd0xaSVZ3NWEvYTBFeXRPc1Vs
            L24xcmcvM0QrWXpHQktXdGpJWDZyUXMKzw8knUs6S8MrZtjbFlogWeC8ZlcTYSB1
            9OzWSSMlO6iZrzmEA+RKmpx5DTX86qFFZeP2pj8lYMYs8d6JBOp07g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:19:51Z"
    mac: ENC[AES256_GCM,data:4qd2EDP6PXjpIu+nuxxn4+B3DSrQPpOQMFAgSjBv5efOqkYV7Vk+iX4lnofKY9OzdYhGxNx5/Qw1CFL/gv/+frglxBZJZV/yxShUyfuWTKYqZuJ1PgHN00o4w8RPw+1dPbaWRfLHYC9zTL+NdH6nRVtWDkSbqPsCSoPrOFbpNJM=,iv:lEH6df5J+ruNOSD3Mzq1fyZsDdG8goxdA0UN1o/xvAM=,tag:W2xOZBr8/oIwSZn2O592Zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
