apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yOaXBXhIRUh6oT98nw==,iv:t6q8q/nUzLtsou7NIv9kf2Eguk2V+BLHMzBdX37HT/I=,tag:QS7t/tSd1qCTvmQ3vaSOmg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:cRSO/7jy9vgRfev6g/49zij68AWeYPhe1KD/5OQWlLFs,iv:M0rC+QBtyhQwothoKq+giOn0ZpZ6mvPPs6DYmaiGT+c=,tag:fESgf5+m0nc08pP0XSLENQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:z2ruErvnSNFWm6jFelc6eu/MVlWUCl/Yj+TW2nf1N5LNfG/B,iv:mJyqZIiZmkOqtg2vHaFskyOPmvu/tZTSgskt348LSJk=,tag:1xzAyAFlYzdAev4rneAzeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OTN5Vk9XRE5lb1I3TGNq
            bi9BK3hubHdHREw5UWZRWFVtaGpyQXQzTXdFCkxrOE56MVdlakFuNm1CR1BqNVdH
            WDZRcDNYYi83ZHNtL3czWnlRRzlXTFEKLS0tIE5QdU1mOWw0cjFCZ2pacUdtNkxu
            MGFHYzF4UTN6WFpyRkovRU0zb05nUkUKrxLQdBLkq5wg5cYKoyOO/NgqifY1Cm+o
            eRmt9eEQ4njQK3KxJtlf66fEpnwvpSdHysp1DX2nsQrIfLdI0jQPfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T01:28:48Z"
    mac: ENC[AES256_GCM,data:k9taiRqYqkKZcFI0tc8iNS07ri/kAmUzR9L4ebKa4hGaKgeA6jgju5ER1WOMHpByq6kVdKmKxXKWfsCRdQTgbvthpMLcho6KB4CRL1efTikVjIpLVoj9hRyyU0vCVmufqDX1cR4aNrGxja5t77sVAPgrhwtTvbDrbWvX7pzqQnk=,iv:ivRN1I3D9+qN9s1XVwaDD+ktCM3V4ABQt9ti/aGLG0c=,tag:o/3CD3k8Ipwv4v6wGBxrSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
