apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lYg1ZkTFp5KUcnSxNQ==,iv:0xnO3x0V6IGWIH11+D/j6zibz6QB/iu8JlI4EPpSi1c=,tag:7gCEIhd8XGo6qzGl0m8Bsw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OtjtjjvRLnH9n9BrHTz3oEGJko1pjr12X+vsX4UBWNFb,iv:/UJ5q4DJgUWVkAzUNDMK86dipGOW6jb6lgQtV553Vwo=,tag:9RwpWSKuKhIOlKtzkZTGCQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EhK8mPByikTyRIsm99QxGzp3IW3Demq8Vpy44vPZ7Y/QNveN,iv:AUiLJRUR+g3PIvK7slurF4Md5rwOgjxws3Kkg7W3uqs=,tag:FXzp/GGrReCTttBGpTX24Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZzJGLzB0MllMWXdZNE16
            YzNRTC9yaXFBNktTSWltQTJTZ2tjNDJvOFc4CmZnWlozZEpJL3EyTG81QlV3STht
            N2hrMS9aYVdqbXhZTjMyaTg0bWRIbHcKLS0tIENPbm13N1d6Snc1KzJNNnZFTS9F
            K3lreEdsNFpyQjFHQ2NteGJkWllqNWsKlpNe8lOvdt8VMQqXfhnV5c7a4DhAYe6F
            9dJsJe09X38Wm32A9rbtNnhPnR8olrGo+bZWttvli7qbNq9hweMJ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T02:15:22Z"
    mac: ENC[AES256_GCM,data:Y5CRYu7vp2o34xeyPHIl9fOIywrEm2WPj14/EVwV8QFrP7WaPBJYlkqxNLV0pAklETD2lCRta5OCLuYzi5FreU99Keaes1rziuSBuy2jFGtvYDcy0pDJ/GC0HDnjysmWgQRV7RtCupqvQmh50l2VubgkgbfWizYqg7m64PotsLw=,iv:lqS8FHBrFFzcBdKhPBBehUzXPe83X0DxhTH8dfqNaRg=,tag:kN3L44FRQZ8wKksqU7OZ/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
