apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ArXQpk1EI6zxh57ZMt5VZa2I8SskQvYEiDaPO5FU0Uw=,iv:Oizn9PCx1LyvrMtqDMgFjO+jVGsNWofchh2/QHz21kc=,tag:lx5xOBaesDrcjf1zmvUY8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWVU2MVQ2Lzl2SDFnYlA5
            ZDBzRGtSaTNjcWs2VTErbktPSG9MWUZDVXowCjJOdWVGbVdoeldUZlUyeU1YZ3Iz
            YVB4UjJRL214NlBFc0VDUTdDY3hmVGcKLS0tIGhrU291NGczWENzQUw1MkY2SXN4
            bytMRFpIWEVreWxNajR3bm45TDR1dlEKRTfyRZmJQjcDqd2MwkDHWJ+EP5khex/u
            KdykPC26YC4hryCeBGt4mMcWi6fEOuJ5OBq3/4ICezFqcjaisc0J9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T23:11:00Z"
    mac: ENC[AES256_GCM,data:ZF39MduU5oHx1/u+vGY3hsBj+OjKduwNYin6/Bn7Pp1vf+pR27AwUqHn5ZedpgADE7l9KCUejmjoA++3zMrDIaKMjBr1gjG0FN+Ui/tWGh59jyIKh96xhPeHTTYK4NOkndRY21sJM6nSzEcLFSRylYhdcC/AsaqvkrgeDk7zjjw=,iv:zoxp1QMymM8kyU7dvYj54/EbxXWHDxWDdS0PWs047N4=,tag:SiuABSCSvoBf6ThLoMo2Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
