apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:hM3h8/tHqcSwkIDlv81CXbUEa1aT1C/vJRzhgjGjMVI=,iv:05ZZ8BSb+TVXqRptVZBVcKZb0Wf7WBK60TMyQ+JPH4Y=,tag:4xqJcRNRSsgYX0wqrmmC5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b25WTXFYWFl0WWdjaWUx
            WHI1NTZyMzVYYjlPOFJsUXdzOGEzQUNnNkVBCnJ0L0RhcHh1VDVSVkh0U2tkVFpK
            M09ZQk5Kc3VxbTI4OFFxR2cxUm9qZG8KLS0tIDh1S3dzNGhFOVF5NUdtTWFzSis0
            dUxPWDF0WWFldWNkQWlYOXNUamlHUkEKQABsItM/SA+NyIVuuY1/ZM3JfZ6kVBEa
            PHVP+5NWhTCSVGaz2JcsccMl69BLiG6+CAih9Rmp2o+QZbQH6xPFUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T13:28:32Z"
    mac: ENC[AES256_GCM,data:r/1OFaAzowvygrGkYJWOxYx8MnL1XCrNtrLhW+q105Dw3EuIjr2wL8zeueueESSzhrfGy2U0MNYcP421hhAtbGq4zlotsU8I9Tp5VKOpYuiTIxKkjLFXEkZSTgGO1ShefmQMqcTirC9EWVlnW84kF1G3Nk7TM5mi6QoALx87y+U=,iv:dUhw0QqOUzEr5QoN6Fg/wKLQLTXRdjS6Oi7UZGr4W8A=,tag:EsrwP9Ju6jwnQCkUUDUUVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
