apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7Kh+dDOie6mRmEaubg/WSUIZOTdqTm/12DR6wLlPsi8=,iv:Qq/AhdxyrJdu4qnKxDklRGXqEbAE8ugfl8OH+lnLTQI=,tag:cQJluvJMGhG0CHm6B/MKEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3JYck84UVVRMVNBQkhI
            YldCWWxUQ29ER1RFS2NpSXV3dzZuSEM0Z3dZClJuWWRVYXFtUmlrVW1XZnlPMHAz
            bHhsbGpRblJXRTBYZ0NjRkVNRTZSTDQKLS0tIEVoQU8zeDBWWWVjU1dDeTM3WDFG
            NWk3N0RNajlhUVlaMW9saWFNQ0lSYjAKsuJHc+6LGOrcnx0lNH52XBJcI17TX+sA
            FDCU7gKPMRR1RWqSuZUuunE8uKxg5Q9DKqRxWYmGTM08jCTYDy4L0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T20:15:58Z"
    mac: ENC[AES256_GCM,data:YDFh2XYnI9hFyKFtVYPJEXF5Hd9llhKz1GBpriAeFs+LUuAPCb3uVZrQihReioCAsMjVArMxAZXc9YxC1JTwk8REycUn7aTh1UMy0nYUZt73ef8yu7kCsb0twNFaqsxWQBNqUm3lB1tfidVePC7/XnopKH7xl9YgephobbRB/i8=,iv:YA4kOBnWebQXnHPVS8PO+wn+CKIP1JATaFt2wvh87MU=,tag:SgwJFamqBBn8PZfMORx1sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
