apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ZlGq1XhInwcCWHRCMI6TyGGpu3UrX+6aJovQWsSDenw=,iv:5PeDn+QM3pYbDMyobErFeJZgZQMR/WzffYdIsmQj9vA=,tag:ihNZmUKjkciTsxP2Asl9zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNHZuNnZwSnczOEo2MGkv
            NUZiTCtWNnhDWTJZejBGNGNwNFN6NW1OWXhzCkhLOVVXMmI4djFYVUY3d1ozV1Jy
            em10dExvdWpiWVlVRkxqNUNtMzcxbncKLS0tIHRqaGQ0ZjVsL2Nnb0M5akhXVjhC
            VzFzT0tEVUZ4M2ZkcWp3SUtvY041QW8KzJRSqcsauz1Ywxeap434Jqe8jbD/95/N
            AoE005pW8rRoB6vs6FL75acijT1V1fXUwnBGNX3I3GFd+PLZfnUNqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:25:02Z"
    mac: ENC[AES256_GCM,data:thQnryQo/0l/FcpTVmuyi/7rM59Iur9UJNUWebNMSDls3HWCeQ5x+RkAmy++DcYM199mRhwLSA5ZgqmH7H/h4CgkNt26foMQMY+z7jv5YCS2IIsqAHJAHumbyVAvDHWFiBeJRHW8flnarC5hy0MvB4JbDFDMFAqfbonCGHHq6UI=,iv:l+SJ7G666j7dacFWzlh0XNEmM7XHc8GqrDjK9Eacd1I=,tag:Rr1efftgjtB1IwOo8qoZ9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
