apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:16p/4ADkCEcwMN0mII7zlKL/b582Q0sde5HPuej4JTw=,iv:Eq/2tYP46+U07U5zl/DVx/enCRgyWnqmIlK/rsy/Huk=,tag:F79oxm9WXhSiCqJ3aEp6EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeUdCRnlTZkJ4RlNOdEFs
            NXIydzZ3T0VMWG1iOVUrUS8yVXpyU3pwUmhVCkxGaGY2dGV6L0EzYjBVU0JwdXFs
            d2dvWTdCNXlYTU1Hc3RCVitwM1AxNTAKLS0tIFBPbXQwT2IxeFhjbDVVU29aRU1a
            Nmp2SVhJcncvZjZ5Qk8walN6ODd5aEUKHAMZWmjGF3o+IsgnU1PaMvLEFl2TTE1M
            6hEw6oXcvo11GsiuVnVCfHvF9NnG7clG5I4gkngxWnAOjVUtaAe5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T22:20:30Z"
    mac: ENC[AES256_GCM,data:XsnRi4IH4NLwNStPFXwNLg3L10Sv/NuGHOFc5YU4R1+fYPeuSbzqxjOHpbH3/z38/qLomIMajP2/Z9bj9i8lT/pwVRIit6ElcHP0GTTyZimBH/f8WjlNPuBlz0UIIsrLeWC0LkqZ7/1fkNKgXiWw1oTHLX7umjBc7RtHJaVr/pI=,iv:cDgt6Ol2qkgwosoo+NoyFiQYm17X/J/DTNkEeoTrKnQ=,tag:F8WzV3cj99AeXSIlrZoMrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
