apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:deE74tCVIW9e2tsDwwNQJxT7P5kn3kq1HigI+PaTGd4=,iv:NHWXpYHmGne+K4VoqpFTao80dOpO+4PX/cdrLbfJKbo=,tag:rWFUnt7EhOW853ItGqStOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dUs3MEhkQW1QMWgvdnc5
            RURxNW1QZ1MzNHFlODlmWTVkMEpzYXBRcjJJCkhlQWJEQUkvRFdPOVhmY3hrdFBR
            WFJ0NjVURzRLWlcycW9BRXNVZjBvTkkKLS0tIGE2b3dEcXdZZVBBZ1N1aHdyM0VY
            US9FU0VPZUtUcURYblp6bmF2OERqeFkKNvDHvA00muzcUoqE9GOttI7v7Gmwt+uf
            H9p6kMWfp7hrtkXIXWHEhhusD4rH59DUdXn7wRiRH4JXcsn52V1MVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T01:28:48Z"
    mac: ENC[AES256_GCM,data:+SU1V/mpX7MxLelAhef9cwg+V05l1rx0XG/riQOwU1Kq8SuB4BkNKd9iWaFvHSTR/MmK9cXaQOnP3zJxbQOeDSh6ala6rpOu6A7VH93wvl1S61L37D6cpxjl3XQ+5y8O96OCbWG8Wb4LMUbtxbFCxNs7iaakNQ0Ptt8GBnAL650=,iv:N/hjO3U0/FOnpsMyh0ZLspJtBSR8C/DE3JrNx/Qnba0=,tag:BRGy217VpJoBoQgBtSkzMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
