apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:FoZljSBIdG0vkmaS2+CI0Z0+WxJs3jhXgJATa2FBYSQ=,iv:JZAJaD2aBB+Hng4G6mbgD4W2vdvLMp+UCy9T3knzHDU=,tag:tPI8SgdARfwJrQ23qxUK4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQVBza1FLOWxGc0QyTWFZ
            UVZNLzRzQ29uMEhTNVhuYUJiS2ZZTDN0bjNJCmx1OGMraWE0VGhyWUNkdWY3dWVv
            Zk5NOFJZNU5STFlmTGx5NWM3Y1VBTm8KLS0tIGJCY0xOa2hoNzFoRkREMDNUL1Fy
            b3Z0YmxPZDRwTVVQV0MvSmFWb3F4NEUK1of4ULU3vtOVSRYjLKbSzMH6d0/Xsiux
            KhZjIQDS7qao+m+ShY/P33+ang/ExHGdotOrFtK+M0+i07yu1l9wJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T13:42:42Z"
    mac: ENC[AES256_GCM,data:MX1KBU83LgvLWcn1ZRoT8oIb8I0rZzcwh+HhhjcDEhTaEKmQ80+Q2Y6BwhbQNfpeaCn5fuHfEm2A+gL810jC1AaMf2fhMTpzcpq1o+lgtj8sCkIzkSQ3mDuagV1sjUG48PWDUKT1ZoOXUFY0JGhshVlx7PUWHQdUyEM2QJ0y/Vc=,iv:/DQ9JZUGp8cycqvcpPNW1XjriwiepNJlHyLW5opu9BU=,tag:42qf0MbdP4zE4qNmG59xUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
