apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lJM60AjVHOAE8GdqVohrym50WceY0CMe6UgUUkMf1sc=,iv:ny9Onyf4kUUFtsJZYBfcWFYQf/sI7QZSZaSaNcCFHrc=,tag:Vuz/IT6uMz5q1XnRjYDQLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaUU1NGRnSTh2YTAySmhP
            N3pHV0NyWm5XTWdHMldpOUFtT3BHL3FRUVRNCjhRMEh0dWpOeFpjRVBtY0RsTnNa
            N1dQWlMySjByMGllZmVFWUsrcnhreHcKLS0tIDZzbmpNYUJ0dDlYNXdRNkg2SGJR
            QmszTlhEOTJZcmF2OFYxRVliV2hkNHcK++xJ53egdJHuBlNWZWDCpeXnCMgwgdSI
            o7eOtpfLXHYOo/YAVA6GhBOvAWCBjKQKpELhG7Y34mB+tbQJ26dBdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T05:49:59Z"
    mac: ENC[AES256_GCM,data:Een63a/1h3I4JtVo+EQkedaW4x4M82xh9m96j7G4lOTjaP26x4D/lZiYshknbfsdJlaRE3KkzGn00cSK8r/2Y9Gs3aSfDcU8jf56Uc+tCNyFJgrSP3T7Vu/kUvc6d99rP4TL+c8Ga3y9q1T8gr4Hbkazc7pmHUOdBXrR6b80liQ=,iv:K+WeTiJsF9EkdqKe1HPf90oupOBv2m3XDiyXEQ7SgPA=,tag:WPAQRAbgvbyoETSdnUzjZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
