apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yOGl/VRzaTdjuvFg5MEaQlzJvAKDNf/kD+NOjO/EWzX8tFusrGbKxA==,iv:RkooaFKDXEAOvUZ+pphKySbDaAfWF8mCUxE1Y1wQ9mc=,tag:lWXH22Oq4NxGIzx/fFE+4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb2NiVzV5d1V4SjF1RVg3
            Wnh6Z3RDOExpaCtTZmh3Nnl1VzQ2Tk1ZVUM4ClFXNHBiUyt3WmJpQWhtM1BTak9B
            RmI1NUV0STNmTERFeFEyVDBYcHRPN0kKLS0tIEJIQUFKNFNHV25ETkZ4WExkYytH
            clA4dy9ra0dzNHFvNnI0cjNNUCtBK2MKtXAs9FuocCNKfnaFkF0Mg00ceNx8B803
            1uBttpltQP6ImSHZQc/xBCXfmtTyL0q3sQUNVrenweBynqneEbSruQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T19:39:43Z"
    mac: ENC[AES256_GCM,data:RJnqjiJxNoJqqC68Ekgxwix6bC6PfNHiLRfzMdXiKYf3Unw/ll5MF+33KsrJVYYtxcFxdGR880fRiU6Ot9lbeNJVKzYOoBQ+YDDs9sJ6ly+LDnyIVncLPla2gIR54sTyXs/JRctW6+bSYjlqO1euYhdAHoaAMZIRdaE4Zb/i37w=,iv:xAwxA4llkzsgJP/yy/vrnq6Vnnqbdm5YfZLdt651TaE=,tag:h/e+TA6ytiaWqUXNHu3J5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
