apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:hd6H21TTrwqOBOd0SeMgmX1Lcu4dw+MeNvQMU6ElFvVjj2ULi1+fbg==,iv:xr8JvTdMfZMRY33TSR7HBVtvQ4wWB904VGitLyxZmEY=,tag:JbkiuEYGhZtm55YXmVS7kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVk5Xb0NnM0ZpbC84MDZK
            dXAwNHBOY1VWVmhBaFJCOUJvNGM2cTNhdVhNCnE2Z0ZVYU5jczRjTU1mVnNFWkdr
            dUVyN3ZPSmdDdUpNK2ExeDM3MU5KYjgKLS0tIHJ3dytUYkNtK3ZKanNCb0lhalh6
            SG9uZnFrMktkejFzck9id0JrUzVzVjQKpYP2XqcwxnPWGcw6OO1dsskPZQXAT8M7
            H97WWUsGGeKXkbXbpLKRJd9xQZEO54V/F/ItSl33XtpYcnE9YzygQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T23:11:00Z"
    mac: ENC[AES256_GCM,data:ppD2Vpb2nIYy5pTt7XFR6hGgVyqZtWoTVJim6A8hJJikJ7+8QpJjSoWx8MQe9TxeaVV7u7nF8NLd/8zt533f9/l05gleOwu6/VxLWU41nHRiKcLN/z9PpjQwli0YthdUehU9m8W8D4hZV3juxaIwmjPZ8YlzbtHWogFz161cjSY=,iv:jVR/WaFoBUOafQ9NeZjfnHHEISRCbNI4CNgeXzXe3ps=,tag:6tIEHiXeBFZlPD5tDMjcqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
