apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Dx0NscYwnv4CclKDyFCgqf4stlICwQC0fwG4785cnHCFyV4TII/ScQ==,iv:fuODlloFv3DkCny2znu64DOXywl9F8+mNj6GZB1QMzs=,tag:D6gsBzDbZtAztHw6Ddkv7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWmFoUWFOemMxV3ZXcHQ4
            eVVONkVKVXorNkpVK2Zyc3Irck1zQVlsbEN3Ckc1UjNkajlPMmxvcGQ0amlIeEp2
            ZGZWaWNDQVFEak1RUkREVTZOaVZVTUUKLS0tIFgxYVJ6YUpVVTY4dUxsU0xDcm80
            dmF3cFJqM1hXUi9Lb21UUklTUEY3UEEKQisyFoOdLJrKgWotmzYPcoBnrlrDfNVb
            FrBMP+AE2PbflRbtUalhj+OwuaNxCqhclWpabaCL3sbYpABZRfky4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:37:26Z"
    mac: ENC[AES256_GCM,data:dX4Nj2+AEmsIjLxkFcYPzVoAZvml+PTNN280p8V+5Vz7eWNEyPLmwURQAE/a0U34mf3ZM/E8uH/eQCGpRbWe9ksbluuvxhIs+2Ys+4LIWns1ai01AekHBL+exHBOAIjhxiY083EA30Vt+07/AlSEMNjaFE7H72RC+4+zC1ewLLs=,iv:ficPdSnFaSnbVobilebwuKPZLhuPMwYWV2UcjvlP6qg=,tag:S/5y9lnbgJ/6O0Pe4Ya5VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
