apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ghvcsNxKUm9BxX3LJU3i/WRconfjdaETwnh3V3F1j5Z2lKe0HLH8Qg==,iv:UP5IRwT9QoZEe6dR7U1Hv4vTaw8t2dHdm1U11f5vg9s=,tag:J7ddCkBdimx77fTl9yTFMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS0dBZEsvYTRDck1WV3BW
            U205cllrNldJZ2drSXZzRXh4NnBTM3lNVlVBCk5rd3pEWjI5L2V1RXIra0N6U2tD
            eStmNUpYTzY1OUNKbFpEbnhiQjZqdVkKLS0tIFYyUnIzY3dvYTZqTW1ZU3VCRGdj
            QTdSUEZ2SEpVMFYxRHlrZkxKUFFJd2sK0uSecPhTwLf31+/gzIBxSQQITlaU8t8M
            jzXogUkorHJXJOovRblNZO8f9+PXALY9TwTqqAmJOmqOrtXtsrAewg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T01:07:49Z"
    mac: ENC[AES256_GCM,data:nkV5iT7d6VUWDEBRIXW7WEgvMl8NMC4lFXwCzxus4UNfV37qHlqo98oXWFzbrt1XgGYldi9YHlc0sDDwCSIBQNkQ5tKoq2wK7/GxOY2CcRFTwm4rxncQMnwLklk/A7ku/FkI46QwX/ig0nJAIKHjArbdj33axXR7BaVKUPxWRsY=,iv:moCzWteHdg6cf5DCiuo4XE/Ux0Sl4J1pp0J0g6t1AgI=,tag:I7wROk0o9KnmA7s0ZFe0eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
