apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Ct9Ggea9rkUpsOu/d5elC2ntUUjqvoVgehmyqYwg0TAHndB4igZQMw==,iv:vt7S+dYI0dmR2jXkDBbB6s85UhT6/rnEW3PeSqsz6yM=,tag:qvgZX2ExKH6uPjWl6YCoWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wng46asecgu7c0tj6waqq3ar974wrdf0cqxeq6f2vw80etq8f7sj93szm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZTVNV0lyUktNYkhBNVZk
            czBybGFUMENDMGNCTzlRMThKSTlTMkNTTVY4Cm9keDd0bVhJMGxXSjBDUmYzMytS
            ZnZQbTRtMzVyc1VwMmZZZmhNQWIwTTAKLS0tIHlYMWRPU1liZ1hTZVgyVW50WFZw
            UmpOZ1B0bFp1TEM0SzBQMG1sRzljdjQKI1G5OML16x4mdjIfWOZwN0ZGN+jwiG8Q
            gB+edbnkfYcz/faA1364Y5Xe8HXmLBmtgplt1CLQ4B3ZraxW9JE/kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:19:51Z"
    mac: ENC[AES256_GCM,data:xe+TgYTdv4IpcsNuqh2JyS+GFLwra8DIgNyl4Z97pgfljvjMCPC+ExtMWgDVIguFEfTEOSAna+/VXaUoSmY8QwQTDDFMwxLnXcnxQId8O6cyliLATK2mzSnlf3DMO5URQY3WT3xgWJV9X1WPwTFs4id9rBNOVxPLirEl2Si8khI=,iv:pDy9v53v+XC/Hq6e/uQzZ2ZDeDGmTWHY9ezQW8Yddm0=,tag:YX4sa8Z2int4HNXw0o7kTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
